### ISSUE TITLE
我也在使用mgop请求时遇到了问题...

### ISSUE THREAD

**Issue by zzzlucas** [winoooops/ZLBGTFO#1]
最近我也开始对接一个浙里办的H5应用，很高兴能在github搜到你的文档，也看到你一直在维护更新，你的文档是对我有一定启发的。
不过还是有问题想问问你：
1、是否踩到了Mgop在政务中台debug工具里请求数据返回data空的情况
![image](https://user-images.githubusercontent.com/37996822/158098809-5c2cdd42-419c-473c-9012-4448d11eda63.png)
2、主要是为了排查第一个问题，我看到‘在对接单点登录之前都可以在浙里办的地址后面加上/debug来访问测试环境的地址’，是指mgop的host: 'https://gov-bus.zjzwfw.gov.cn'改为host: 'https://gov-bus.zjzwfw.gov.cn/debug'吗？irs开发文档里是没看到这个说法。

**Comment by winoooops** [comment]
谢谢你的回复, 很高兴能帮到你一些.

1.这个你有IRS开发商工作台里联调过吗? 封装的组件是类似我文章里的吗? 里面是json格式吗?
2. 域名应该是以`https://xxx.com/doman?debug=true`的形式存在, 这个可以和对接群里的老师确认一下, 如果涉及到单点登录的话就得让他们帮忙重新配置

**Comment by zzzlucas** [comment]
> 

后续我这里明确情况，发现是ios上的浙里办app联调debug工具，请求data为空；安卓上的浙里办app联调debug工具，请求data得到正确数据。踩到了这么一个坑。

**Comment by winoooops** [comment]
你们有遇到过应用在移动网络的环境下接口无法访问的问题吗? 之前群里好多人在反映这个问题.

**Comment by zzzlucas** [comment]
我们还没到这个进度节点

**Comment by Clago** [comment]
mgop出口地址能配置外网地址吗？
