### ISSUE TITLE
一些问题请教

### ISSUE THREAD

**Issue by ltinerary** [winoooops/ZLBGTFO#2]
您好，最近需要对接浙里办应用。我这边刚开始看，搜到了您的文章。
我想请教一下，你这边的process.env.NODE_ENV的值是自己定义的？自己设置的环境变量？还是在浙里办或者支付宝小程序里这个值的变量是由浙里办容器环境提供的？
![ceaaeec4b05e269faec5bdc7e453c67](https://user-images.githubusercontent.com/79144923/180910899-d6277bfa-e743-439a-b5a4-fc7f033d72ba.png)

**Comment by winoooops** [comment]
这个是自己定义的, 只要这个环境变量的值对应着`package.json`里面`npm build`的环境变量就可以了
![image](https://user-images.githubusercontent.com/33833816/180935035-3d7bfc7a-82d4-418b-a9fe-647e4b498a94.png)

**Comment by ltinerary** [comment]
> 这个是自己定义的, 只要这个环境变量的值对应着`package.json`里面`npm build`的环境变量就可以了 ![image](https://user-images.githubusercontent.com/33833816/180935035-3d7bfc7a-82d4-418b-a9fe-647e4b498a94.png)

好的，十分感谢。您的文章对我初次对接浙里办十分有启发🤩
