### ISSUE TITLE
rs:3005,memo:"appId对应的APP不存在"

### ISSUE THREAD

**Issue by badspider7** [winoooops/ZLBGTFO#4]
你好，我想问一下这个错误码是什么意思呢，没有加群，照着文档来配置api，是因为步骤的问题吗，还是app需要上线才能测试。

**Comment by winoooops** [comment]
这个请加浙政厅的应用开发群， 里面有份文档可以查看错误代码和提示，群里的工作人员也可以帮忙解答。我这个文档2年前写的， 可能很多细节都变了。
